In [1]:
import numpy as np

In [9]:
# making list like [[],[],[]]

x = [list(range(0,6)),list(range(9,15)),list(range(20,26))]

In [10]:
x

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14], [20, 21, 22, 23, 24, 25]]

In [17]:
# convert list to array

xnp = np.array(x)

In [18]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

## Indexing

In [19]:
x[0]

[0, 1, 2, 3, 4, 5]

In [20]:
x[0][1]

1

In [21]:
x[0][-1]

5

In [22]:
xnp[0][1]

1

In [23]:
xnp[0][-1]

5

#### so far list and NumPy follows same, but NumPy allows to retrieve in same index

In [26]:
# nparray[row, column]

xnp[0, -1]

5

In [28]:
xnp[0, 1]

1

In [29]:
# CAN NOT do in list

x[0, 1]

TypeError: list indices must be integers or slices, not tuple

## Slicing

In [31]:
# CAN NOT do slicing like this in list

x[0:1, 1:2]

TypeError: list indices must be integers or slices, not tuple

In [33]:
# can call whole list

x[0:2]

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14]]

In [35]:
# slicing is easy for 2D numpy array

xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [37]:
# remember, last is not included, so 0,1 rows and 1,2,3 columns

xnp[0:2,1:4]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [38]:
xnp[0]

array([0, 1, 2, 3, 4, 5])

In [40]:
# from row 1, taking 3,4 columns value

xnp[1, 3:5]

array([12, 13])

#### this is slicing or subsetting in this case

## Logical Indexing

In [41]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [42]:
xnp > 10

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [43]:
xnp[xnp>10]

array([11, 12, 13, 14, 20, 21, 22, 23, 24, 25])

In [44]:
# retrieving all rows and column 2

xnp[:,2]

array([ 2, 11, 22])

In [45]:
xnp[:,2] > 10

array([False,  True,  True])

In [46]:
# first select the values, 
# second check the condition, 
# and by combining you will get the values for which the condition is true

xnp[:,2][xnp[:,2] > 10]

array([11, 22])

In [48]:
xnp[:,2:5][xnp[:,2] > 10]

array([[11, 12, 13],
       [22, 23, 24]])

In [49]:
xnp[:,2:5][xnp[:,2] > 13]

array([[22, 23, 24]])

In [50]:
xnp[2]

array([20, 21, 22, 23, 24, 25])

In [51]:
xnp[2, :]

array([20, 21, 22, 23, 24, 25])